/* eslint-disable jsdoc/require-file-overview */
module.exports = {
  extends: ['plugin:jsdoc/recommended'],
  plugins: ['jsdoc'],
  rules: {
    'jsdoc/check-access': 'warn',
    'jsdoc/check-alignment': 'warn',
    'jsdoc/check-examples': 'off', // This rule is buggy
    'jsdoc/check-indentation': 'warn',
    'jsdoc/check-line-alignment': 'off',
    'jsdoc/check-param-names': ['warn', { enableFixer: false }],
    'jsdoc/check-property-names': ['warn', { enableFixer: false }],
    'jsdoc/check-syntax': 'warn',
    'jsdoc/check-tag-names': 'warn',
    'jsdoc/check-types': 'warn',
    'jsdoc/check-values': 'warn',
    'jsdoc/empty-tags': 'warn',
    'jsdoc/implements-on-classes': 'warn',
    'jsdoc/match-description': 'warn',
    'jsdoc/newline-after-description': 'warn',
    'jsdoc/no-bad-blocks': 'warn',
    'jsdoc/no-defaults': 'warn',
    'jsdoc/no-types': 'off',
    'jsdoc/no-undefined-types': 'warn',
    'jsdoc/require-description': 'warn',
    'jsdoc/require-description-complete-sentence': [
      'warn',
      {
        tags: ['see', 'copyright', 'deprecated'],
      },
    ],
    'jsdoc/require-example': [
      'off', // Disabling for now because it adds empty @example tags to all functions, breaking doc generation
      {
        exemptNoArguments: true,
      },
    ],
    'jsdoc/require-file-overview': [
      'warn',
      {
        tags: {
          module: {
            initialCommentsOnly: true,
            mustExist: true,
            preventDuplicates: true,
          },
        },
      },
    ],
    'jsdoc/require-hyphen-before-param-description': ['warn', 'always'],
    'jsdoc/require-jsdoc': [
      'warn',
      {
        publicOnly: true,
        require: { ArrowFunctionExpression: false, FunctionExpression: false },
        enableFixer: false,
      },
    ],
    'jsdoc/require-param': [
      'warn',
      {
        enableFixer: true,
        unnamedRootBase: ['params'],
      },
    ],
    'jsdoc/require-param-description': 'warn',
    'jsdoc/require-param-name': 'warn',
    'jsdoc/require-param-type': 'warn',
    'jsdoc/require-property': 'warn',
    'jsdoc/require-property-description': 'warn',
    'jsdoc/require-property-name': 'warn',
    'jsdoc/require-property-type': 'warn',
    'jsdoc/require-returns': 'warn',
    'jsdoc/require-returns-check': 'warn',
    'jsdoc/require-returns-description': 'warn',
    'jsdoc/require-returns-type': 'warn',
    'jsdoc/require-throws': 'warn',
    'jsdoc/valid-types': 'warn',
  },
  overrides: [
    {
      files: [
        '*_spec.+(js|ts|md)?(x)',
        '*.+(stories|test|spec).+(js|ts|md)?(x)',
      ],
      rules: {
        'jsdoc/check-access': 'off',
        'jsdoc/check-alignment': 'off',
        'jsdoc/check-examples': 'off',
        'jsdoc/check-indentation': 'off',
        'jsdoc/check-line-alignment': 'off',
        'jsdoc/check-param-names': 'off',
        'jsdoc/check-property-names': 'off',
        'jsdoc/check-syntax': 'off',
        'jsdoc/check-tag-names': 'off',
        'jsdoc/check-types': 'off',
        'jsdoc/check-values': 'off',
        'jsdoc/empty-tags': 'off',
        'jsdoc/implements-on-classes': 'off',
        'jsdoc/match-description': 'off',
        'jsdoc/newline-after-description': 'off',
        'jsdoc/no-bad-blocks': 'off',
        'jsdoc/no-defaults': 'off',
        'jsdoc/no-types': 'off',
        'jsdoc/no-undefined-types': 'off',
        'jsdoc/require-description': 'off',
        'jsdoc/require-description-complete-sentence': 'off',
        'jsdoc/require-example': 'off',
        'jsdoc/require-file-overview': 'off',
        'jsdoc/require-hyphen-before-param-description': 'off',
        'jsdoc/require-jsdoc': 'off',
        'jsdoc/require-param': 'off',
        'jsdoc/require-param-description': 'off',
        'jsdoc/require-param-name': 'off',
        'jsdoc/require-param-type': 'off',
        'jsdoc/require-property': 'off',
        'jsdoc/require-property-description': 'off',
        'jsdoc/require-property-name': 'off',
        'jsdoc/require-property-type': 'off',
        'jsdoc/require-returns': 'off',
        'jsdoc/require-returns-check': 'off',
        'jsdoc/require-returns-description': 'off',
        'jsdoc/require-returns-type': 'off',
        'jsdoc/require-throws': 'off',
        'jsdoc/valid-types': 'off',
      },
    },
  ],
}
